name: Metal Price Daily Push

# 定时：每天 北京时间早上8点 运行
# cron 是 UTC 时间，比北京时间慢8小时
# 北京 08:00 → UTC 00:00
on:
  schedule:
    - cron: '0 0 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4.2.1

      - name: 配置Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 运行爬虫并发邮件
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PWD: ${{ secrets.SENDER_PWD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: python main.py
